### ISSUE TITLE
Fatal Uncaught Error in WP CLI

### ISSUE THREAD

**Issue by dws122** [stephenharris/Event-Organiser#421]
Using WP CLI V1.4.0 
Event Organiser 3.4.0
Event Organiser Discount Codes 1.3.2
Event Organiser Pro 1.11.11

WordPress 4.8.2
PHP 5.6, 7.0, and 7.1

```
[user@host www]$ wp search-replace 'thiss' 'thatt' --dry-run
Fatal error: Uncaught Error: Call to undefined function wp_hash() in /home/user/public_html/wp-content/plugins/plugin-name-removed/includes/add-on.php:282
Stack trace:
#0 /home/user/public_html/wp-content/plugins/event-organiser-discount-codes/includes/add-on.php(248): eventorganiser_dc_PLM_Update_Handler->get_remote_plugin_info('plugin_info')
#1 /home/user/public_html/wp-includes/class-wp-hook.php(300): eventorganiser_dc_PLM_Update_Handler->check_update(Object(stdClass))
#2 /home/user/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Object(stdClass), Array)
#3 /home/user/public_html/wp-includes/option.php(1662): apply_filters('pre_set_site_tr...', Object(stdClass), 'update_plugins')
#4 /home/user/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/CLI_Integration.php(59): set_site_transient('update_plugins', Object(stdClass))
#5 /home/user/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/CLI_Integration.php(45): Fragen\GitHub_Updater\CLI_I in /home/hsteel20/public_html/wp-content/plugins/event-organiser-discount-codes/includes/add-on.php on line 282
```

**Comment by stephenharris** [comment]
WP Cli 1.4.1 was released a few days ago, does that fix the issue for you (I can't replicate it myself, and `wp_hash()` should be available there).
