### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Grateful-Viv** [stephenharris/Event-Organiser#526]
Not sure if this is related to the WP upgrade to 6.1.

Event previews fine. After publishing, it gives a critical error.

Fatal error: Uncaught Exception: Error in formating DateTime object. Expected DateTime, but instead given boolean in /mydomain.org/public_html/wp-content/plugins/event-organiser/includes/event-organiser-utility-functions.php:31 Stack trace: #0 /mydomain.org/public_html/wp-content/plugins/event-organiser/includes/event-organiser-utility-functions.php(164): eo_format_datetime(false, ‘F j, Y g:i a’) #1 /mydomain.org/public_html/wp-content/plugins/event-organiser/templates/event-meta-event-single.php(86): eo_format_event_occurrence() #2 /mydomain.org/public_html/wp-includes/template.php(785): require(‘/home/customer/…’) #3 /mydomain.org/public_html/wp-content/plugins/event-organiser/includes/event-organiser-templates.php(96): load_template(‘/home/customer/…’, false) #4 /mydomain.org/public_html/wp-content/plugins/event-organiser/includes/event-o in /mydomain.org/public_html/wp-content/plugins/event-organiser/includes/event-organiser-utility-functions.php on line 31
There has been a critical error on this website.

**Comment by picard102** [comment]
Have this happening as well.
